name: Run Selenium Tests

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]
  workflow_dispatch:  # allow manual run

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Use a Selenium standalone Chrome container (headless browser)
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade pytest pytest-html selenium webdriver_manager

      - name: Verify pytest installation
        run: |
          python -m pytest --version
          
      - name: Run Selenium tests with pytest
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: |
          pytest -v
